SELECT *, ROW_NUMBER() OVER (ORDER BY X DESC) AS ROW_ID INTO #TEMP FROM Functions

SELECT DISTINCT B.X, B.Y
FROM #TEMP A JOIN #TEMP B
ON A.X = B.Y AND A.Y = B.X AND A.ROW_ID <> B.ROW_ID
WHERE A.ROW_ID <> B.ROW_ID
ORDER BY B.X ASC